#!/usr/bin/env bash

if [ ! -f ~/.netrc ] || \
    ( [ -f ~/.netrc ] && ! grep -q "goproxy.githubapp.com" ~/.netrc )
then
    if [[ $GO_PROXY_PAT ]]; then
      echo "machine goproxy.githubapp.com login nobody password $GO_PROXY_PAT" >> $HOME/.netrc
    fi
fi

