#!/usr/bin/env bash

if [ ! -f ~/.netrc ] || \
    ( [ -f ~/.netrc ] && ! grep -q "goproxy.githubapp.com" ~/.netrc )
then
    if [[ $GOPROXY_TOKEN ]]; then
      echo "machine goproxy.githubapp.com login nobody password $GOPROXY_TOKEN" >> $HOME/.netrc
    fi
fi

